### PR TITLE
Refactor Form.RichText component to use Quill

### PR DESCRIPTION
**Pull request by Jamie-n**
Refactor FormRichText to use `quill` instead of `react-quill` to enable us to use the mention plugin as this isn't supported by `react-quill`.

> [!CAUTION]
 Due to an ongoing issue, anything using this package will have to directly import the `FormRichText` component and use it as `<FormRichText>` rather than `<Form.RichText>`.
 
 The `onChange` handler has also changed and will not be compatible with directly injecting states into the prop, instead `(value) =>  setFoo(value)` will need to be used.

### CODE REVIEW

**Comment by jsteeland** [comment]
@kishannareshpal are you able to offer any input on what's going on with the `FormRichText`/`Form.RichText` import (caution note in description)? No worries if not, just thought you mind have an idea

**Comment by jamesridgway** [comment]
What's happening with this branch? It looks super old?

**Comment by jsteeland** [comment]
This can likely be closed - this PR was for the tasks project but the UI components are now baked into that repo instead. Do you agree @Jamie-n?

**Comment by Jamie-n** [comment]
> This can likely be closed - this PR was for the tasks project but the UI components are now baked into that repo instead. Do you agree @Jamie-n?

Yeah I agree, this PR can be closed. The features and changes within this branch are now included directly in the tasks project.

**Pull request closed without merging**
